spring:
  application:
    # 设置这个微服务项目的项目名
    name: service-order
  cloud:
    nacos:
      # Nacos 地址，不配置也行，默认是本地的 8848 端口
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        # 控制台地址
        dashboard: localhost:8080
      # 立即加载服务
      eager: true
  config:
    # 添加 Nacos 配置，项目启动后，导入 service-order.yaml 这个配置文件
    import:
      - nacos:service-order.yaml

server:
  # 设置这个微服务项目的端口号
  port: 8000

logging:
  level:
    # 指定 feign 接口所在的包的日志级别为 debug 级别
    com.sangui.order.feign: debug

feign:
  sentinel:
    enabled: true
